# Generated by Django 2.0 on 2020-09-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=50)),
                ('plataform', models.CharField(choices=[('Multi', 'MULTI'), ('PC', 'PC'), ('Playstation', 'PLAYSTATION'), ('Xbox', 'XBOX'), ('Nintendo', 'NINTENDO'), ('Sega', 'SEGA'), ('Game Boy', 'GAME BOY'), ('Mobil', 'MOBIL')], default='Multi', max_length=6)),
                ('genre', models.CharField(choices=[('Acción', 'ACCION'), ('Plataformas', 'PLATAFORMAS'), ('Deporte', 'DEPORTE'), ('Carrera', 'CARRERA'), ('Terror', 'TERROR'), ('Estrategia', 'ESTRATEGIA'), ('Educativo', 'EDUCATIVO'), ('RPG', 'RPG'), ('MMORPG', 'MMORPG'), ('Sandbox', 'SANDBOX'), ('Battle Royale', 'BATTLE ROYALE')], default='Acción', max_length=6)),
                ('review', models.CharField(max_length=2000)),
                ('score', models.IntegerField(choices=[('Obra maestra', 'OBRA MAESTRA'), ('Excelente', 'EXCELENTE'), ('Muy bueno', 'MUY BUENO'), ('Bueno', 'BUENO'), ('Regular', 'REGULAR'), ('Malo', 'MALO'), ('Muy malo', 'MUY MALO'), ('Pésimo', 'PESIMO'), ('No lo compres', 'NO LO COMPRES')], default='Regular', max_length=6)),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
    ]
