# Generated by Django 2.0 on 2020-09-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.CharField(choices=[('Obra maestra', 'OBRA MAESTRA'), ('Excelente', 'EXCELENTE'), ('Muy bueno', 'MUY BUENO'), ('Bueno', 'BUENO'), ('Regular', 'REGULAR'), ('Malo', 'MALO'), ('Muy malo', 'MUY MALO'), ('Pésimo', 'PESIMO'), ('No lo compres', 'NO LO COMPRES')], default='Regular', max_length=6),
        ),
    ]
