# Generated by Django 2.0 on 2020-09-09 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsapp', '0002_auto_20200909_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='image',
            new_name='cover',
        ),
        migrations.AddField(
            model_name='reviews',
            name='release_year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='game_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='genre',
            field=models.CharField(choices=[('Acción', 'ACCION'), ('Plataformas', 'PLATAFORMAS'), ('Deporte', 'DEPORTE'), ('Carrera', 'CARRERA'), ('Terror', 'TERROR'), ('Estrategia', 'ESTRATEGIA'), ('Educativo', 'EDUCATIVO'), ('RPG', 'RPG'), ('MMORPG', 'MMORPG'), ('Sandbox', 'SANDBOX'), ('Battle Royale', 'BATTLE ROYALE')], default='Acción', max_length=30),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='plataform',
            field=models.CharField(choices=[('Multi', 'MULTIPLATAFORMA'), ('PC', 'PC'), ('Playstation', 'PLAYSTATION'), ('Xbox', 'XBOX'), ('Nintendo', 'NINTENDO'), ('Sega', 'SEGA'), ('Game Boy', 'GAME BOY'), ('Mobil', 'MOBIL')], default='Multi', max_length=30),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.CharField(choices=[('Obra maestra', 'OBRA MAESTRA'), ('Excelente', 'EXCELENTE'), ('Muy bueno', 'MUY BUENO'), ('Bueno', 'BUENO'), ('Regular', 'REGULAR'), ('Malo', 'MALO'), ('Muy malo', 'MUY MALO'), ('Pésimo', 'PESIMO'), ('No lo compres', 'NO LO COMPRES')], default='Regular', max_length=30),
        ),
    ]
