# Generated by Django 2.1.7 on 2020-09-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsapp', '0003_auto_20200909_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='cover',
            field=models.ImageField(upload_to='reviewsapp_covers'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='genre',
            field=models.CharField(choices=[('Acción', 'ACCION'), ('Plataformas', 'PLATAFORMAS'), ('FPS', 'FPS'), ('Deporte', 'DEPORTE'), ('Carrera', 'CARRERA'), ('Terror', 'TERROR'), ('Estrategia', 'ESTRATEGIA'), ('Educativo', 'EDUCATIVO'), ('RPG', 'RPG'), ('MMORPG', 'MMORPG'), ('Sandbox', 'SANDBOX'), ('Battle Royale', 'BATTLE ROYALE')], default='Acción', max_length=30),
        ),
    ]
