# Generated by Django 2.1.7 on 2020-09-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsapp', '0005_auto_20200909_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='status',
            field=models.CharField(choices=[('Aprobado', 'APROBADO'), ('Revisar', 'REVISAR'), ('No aprobado', 'NO APROBADO')], default='Revisar', max_length=30),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(),
        ),
    ]
