# Generated by Django 2.1.7 on 2020-09-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsapp', '0006_auto_20200916_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
